export const _selectTokenOptions = [
      {
        "id":0,
        "logo":"token_logo0",
        "value":"MATIC",
        "label":"MATIC",
        "contract_address":"0x0000000000000000000000000000000000000000",
        "decimals":18
      },
      {
         "id":1,
         "logo":"token_logo4",
         "value":"wMATIC",
         "label":"wMATIC",
         "contract_address":process.env.REACT_APP_WMATIC_CONTRACT_ADDRESS,
         "decimals":18
      },
      {
         "id":2,
         "logo":"token_logo1",
         "value":"USDT ERC20",
         "label":"USDT ERC20",
         "contract_address":process.env.REACT_APP_USDT_CONTRACT_ADDRESS,
         "decimals":6
      },
      {
         "id":3,
         "logo":"token_logo2",
         "value":"USDC ERC20",
         "label":"USDC ERC20",
         "contract_address":process.env.REACT_APP_USDC_CONTRACT_ADDRESS,
         "decimals":6
      },
      {
         "id":4,
         "logo":"token_logo3",
         "value":"BUSD ERC20",
         "label":"BUSD ERC20",
         "contract_address":process.env.REACT_APP_BUSD_CONTRACT_ADDRESS,
         "decimals":18
      },
      {
         "id":5,
         "logo":"token_logo5",
         "value":"ETH",
         "label":"ETH",
         "contract_address":process.env.REACT_APP_ETH_CONTRACT_ADDRESS,
         "decimals":18
      },
      {
         "id":6,
         "logo":"token_logo6",
         "value":"BTC",
         "label":"BTC",
         "contract_address":process.env.REACT_APP_BTC_CONTRACT_ADDRESS,
         "decimals":18
      },
      {
         "id":7,
         "logo":"token_logo7",
         "value":"BNB",
         "label":"BNB",
         "contract_address":process.env.REACT_APP_BNB_CONTRACT_ADDRESS,
         "decimals":18
      },
      {
         "id":8,
         "logo":"token_logo8",
         "value":"Aave",
         "label":"Aave",
         "contract_address":process.env.REACT_APP_AAVE_CONTRACT_ADDRESS,
         "decimals":18
      },
      {
         "id":9,
         "logo":"token_logo9",
         "value":"LINK",
         "label":"LINK",
         "contract_address":process.env.REACT_APP_LINK_CONTRACT_ADDRESS,
         "decimals":18
      },
      {
         "id":10,
         "logo":"token_logo10",
         "value":"Luna",
         "label":"Luna",
         "contract_address":process.env.REACT_APP_LUNA_CONTRACT_ADDRESS,
         "decimals":6
      },
      {
         "id":11,
         "logo":"token_logo11",
         "value":"MANA",
         "label":"MANA",
         "contract_address":process.env.REACT_APP_MANA_CONTRACT_ADDRESS,
         "decimals":18
      },
      {
         "id":12,
         "logo":"token_logo12",
         "value":"SAND",
         "label":"SAND",
         "contract_address":process.env.REACT_APP_SAND_CONTRACT_ADDRESS,
         "decimals":18
      }
  ]